stages:
  - build-and-deploy

deploy_job:
  stage: build-and-deploy
  image: alpine:latest
  before_script:
    # install git, ssh, dan grep untuk linting ringan
    - apk add --no-cache git openssh-client grep
    - eval $(ssh-agent -s)
    
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$GITHUB_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.name "GitLab CI Bot"
    - git config --global user.email "ci-bot@gitlab-edu.itb.ac.id"
  script:
    - echo "Checking HTML files for duplicate IDs..."
    - '! grep -E -n "id=\"[^\"]*\"[[:space:]]+id=" *.html'
    
    # deploy ke GitHub branch production
    - GITHUB_REPO_URL="git@github.com:BerthaSoliany/photobooth.git"
    - git checkout -B production
    - git remote add github_origin \(GITHUB_REPO_URL || git remote set-url github_origin\)GITHUB_REPO_URL
    - git push github_origin production --force
  only:
    - main
